

PLACEHOLDER_VALUES_P1 = {
    "ACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Activate Advanced Call Management Features for Incoming and Outgoing Calls",
    "ACTIVATION_SECTION": "Official Service Activation and Customer Onboarding Portal",
    "APP": "TelcoConnect Mobile Application for Comprehensive Account Management",
    "BILLING_SECTION": "Centralized Billing, Invoice Processing, and Reconciliation Unit",
    "CALL_ALERT": "Standard Missed Call and Voicemail Alert Notification System",
    "CANCELLATION_FEES_SUBSECTION": "Policy Regarding Early Termination Penalties and Cancellation Fees",
    "CANCEL_PLAN_OPTION": "Submit Formal Request for Plan Cancellation and Service Termination",
    "CANCEL_SECTION": "Cancellation Processing and Account Termination Division",
    "CHANGE_PLAN_OPTION": "Request Adjustment to Service Subscription through Upgrade or Downgrade",
    "CHECK_EXCESS_DATA_CHARGES_OPTION": "Audit and Review All Additional Mobile Data Usage Charges",
    "COMPANY": "GlobalTel Communications Incorporated",
    "COMPENSATION_REQUEST_OPTION": "Initiate a Claim for Customer Compensation or Financial Refund",
    "COMPENSATION_SECTION": "Department for Service Credit, Refunds, and Compensation Claims",
    "CURRENT_PROVIDER": "Skyline Mobile Telecommunications Provider",
    "CUSTOMER_SUPPORT_NUMBER": "Corporate Customer Care Line: 1-800-555-0199",
    "DATA_SECTION": "Official Mobile Data Usage Monitoring and Compliance Records",
    "DAYS_NUMBER": "5 Business Days (Processing Timeframe)",
    "DEACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Deactivate All Enhanced Call Forwarding, Blocking, and Screening Features",
    "DEACTIVATE_PHONE_OPTION": "Request Device Suspension from Core Telecommunications Network",
    "DEVICE_SECTION": "Enterprise-Registered Devices and Authorized Equipment Catalog",
    "DEVICE_TYPE": "Latest Generation Corporate-Grade 5G Smartphone",
    "DISPUTE_INVOICE_OPTION": "Initiate Formal Invoice Dispute and Investigation Request",
    "EDIT_OPTION": "Edit Official Account Preferences and Corporate Information",
    "FEE_OPTION": "List of Applicable Tariffs, Surcharges, and Administrative Fees",
    "HUMAN_AGENT_OPTION": "Escalate Request to Licensed Human Customer Support Agent",
    "INFORMATION_DATA_CHARGES_SECTION": "Reference Document on Mobile Data Usage and Applicable Fees",
    "INTERNATIONAL_ROAMING_OPTION": "Enable International Roaming in Accordance with Travel Policy",
    "INTERNET_SECTION": "Fixed-Line and Broadband Internet Service Information",
    "INVOICE_SECTION": "Detailed Invoice History and Comprehensive Billing Archive",
    "MANAGEMENT_SERVICES_SECTION": "Centralized Call and Data Management Services Dashboard",
    "MY_ACCOUNT_SECTION": "Secure Customer Account Access Portal",
    "NEW_PROVIDER": "NovaTel Wireless Services Provider",
    "NO_VOICEMAIL": "Voicemail Functionality Disabled by Policy",
    "PAYMENT_HISTORY_OPTION": "Retrieve Archived Payment Transactions and Receipts",
    "PAYMENT_METHODS_OPTION": "Manage Bank Transfer, Credit, and Debit Payment Methods",
    "PAYMENT_SECTION": "Payments and Transaction Management Center",
    "PLAN_SECTION": "Mobile Service Plans and Subscription Management Center",
    "PORTING_CODE": "PORT-987654321-VALID-FOR-7-DAYS",
    "REPORT_POOR_SIGNAL_COVERAGE_OPTION": "Submit Formal Report for Signal Coverage Deficiencies",
    "REPORT_PROBLEM_OPTION": "Log Service Issue or Technical Problem Report",
    "ROAMING_SECTION": "Roaming Services Information and Usage Compliance",
    "SCHEDULE_PAYMENTS_OPTION": "Configure Scheduled or Recurring Payments via Account Portal",
    "SEARCH_BUTTON": "Search Internal Information and Service Catalog",
    "SERVICE_TYPE": "Mobile Voice and Data Communication Service",
    "SIGNAL_COVERAGE_SECTION": "Signal Coverage and Network Availability Reference Maps",
    "SIGN_UP_BUTTON": "Register for a New Subscription Plan",
    "SUPPORT_EMAIL_ADDRESS": "customer.support@globaltel.com",
    "SUPPORT_SECTION": "Customer Support and Service Resolution Division",
    "SUPPORT_TEAM_CONTACT": "Official Support Team Contact Information",
    "SWITCH_ON_OPTION": "Activate Requested Service Feature",
    "USAGE_INFORMATION_OPTION": "Access Consumption Data and Detailed Usage Records",
    "USAGE_SECTION": "Service Consumption and Data Usage Tracking System",
    "VIEW_PAST_BILLS": "Retrieve Archived Billing Records and Payment Documentation",
    "VOICEMAIL": "Voicemail Message Repository and Access Console",
    "WEBSITE_URL": "www.globaltel-communications.com"
}

PLACEHOLDER_VALUES_P2 = {
    "ACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Switch On Spam Shield, Quick Forward, and Instant Screen",
    "ACTIVATION_SECTION": "Start-Up Zone",
    "APP": "PocketTalk App — Chat, Bills, Rewards",
    "BILLING_SECTION": "Money Page",
    "CALL_ALERT": "Buzz Me When I Miss Calls",
    "CANCELLATION_FEES_SUBSECTION": "Quit Costs",
    "CANCEL_PLAN_OPTION": "End My Bundle Now",
    "CANCEL_SECTION": "Exit Hub",
    "CHANGE_PLAN_OPTION": "Pick Another Deal",
    "CHECK_EXCESS_DATA_CHARGES_OPTION": "Extra Costs Log",
    "COMPANY": "TalkNow Crew",
    "COMPENSATION_REQUEST_OPTION": "Get Cashback",
    "COMPENSATION_SECTION": "Rewards Zone",
    "CURRENT_PROVIDER": "MetroWave",
    "CUSTOMER_SUPPORT_NUMBER": "Hotline: +1-888-777-4242",
    "DATA_SECTION": "Consumption Tracker",
    "DAYS_NUMBER": "Two Weeks",
    "DEACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Turn Filters Off",
    "DEACTIVATE_PHONE_OPTION": "Shut My Line",
    "DEVICE_SECTION": "Gadget Locker",
    "DEVICE_TYPE": "Foldable Pocket Device",
    "DISPUTE_INVOICE_OPTION": "Fix My Bill",
    "EDIT_OPTION": "Update Profile",
    "FEE_OPTION": "Charges List",
    "HUMAN_AGENT_OPTION": "Talk to a Person",
    "INFORMATION_DATA_CHARGES_SECTION": "Overage Guide",
    "INTERNATIONAL_ROAMING_OPTION": "Travel Pack",
    "INTERNET_SECTION": "Superfast Deals",
    "INVOICE_SECTION": "Bills Archive",
    "MANAGEMENT_SERVICES_SECTION": "Control Hub",
    "MY_ACCOUNT_SECTION": "Dashboard",
    "NEW_PROVIDER": "HorizonCell",
    "NO_VOICEMAIL": "No Voicemail",
    "PAYMENT_HISTORY_OPTION": "Payment Log",
    "PAYMENT_METHODS_OPTION": "Change Cards",
    "PAYMENT_SECTION": "Pay Here",
    "PLAN_SECTION": "Browse Bundles",
    "PORTING_CODE": "MOVE-NEW-999",
    "REPORT_POOR_SIGNAL_COVERAGE_OPTION": "Bad Signal Ticket",
    "REPORT_PROBLEM_OPTION": "Something’s Wrong",
    "ROAMING_SECTION": "Travel Add-Ons",
    "SCHEDULE_PAYMENTS_OPTION": "Auto-Pay Setup",
    "SEARCH_BUTTON": "Find Now",
    "SERVICE_TYPE": "Talk + Net Pack",
    "SIGNAL_COVERAGE_SECTION": "5G/6G Map",
    "SIGN_UP_BUTTON": "Join Instantly",
    "SUPPORT_EMAIL_ADDRESS": "care@talknow.net",
    "SUPPORT_SECTION": "Help Hub",
    "SUPPORT_TEAM_CONTACT": "Reach Crew",
    "SWITCH_ON_OPTION": "Turn It On",
    "USAGE_INFORMATION_OPTION": "Check My Use",
    "USAGE_SECTION": "Live Feed",
    "VIEW_PAST_BILLS": "Old Bills Log",
    "VOICEMAIL": "Inbox",
    "WEBSITE_URL": "www.talknow.net"
}