PLACEHOLDER_VALUES_P1 = {
    "ACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Activate Advanced Call Management Features for Incoming and Outgoing Calls",
    "ACTIVATION_SECTION": "Official Service Activation and Customer Onboarding Portal",
    "APP": "TelcoConnect Mobile Application for Comprehensive Account Management",
    "BILLING_SECTION": "Centralized Billing, Invoice Processing, and Reconciliation Unit",
    "CALL_ALERT": "Standard Missed Call and Voicemail Alert Notification System",
    "CANCELLATION_FEES_SUBSECTION": "Policy Regarding Early Termination Penalties and Cancellation Fees",
    "CANCEL_PLAN_OPTION": "Submit Formal Request for Plan Cancellation and Service Termination",
    "CANCEL_SECTION": "Cancellation Processing and Account Termination Division",
    "CHANGE_PLAN_OPTION": "Request Adjustment to Service Subscription through Upgrade or Downgrade",
    "CHECK_EXCESS_DATA_CHARGES_OPTION": "Audit and Review All Additional Mobile Data Usage Charges",
    "COMPANY": "GlobalTel Communications Incorporated",
    "COMPENSATION_REQUEST_OPTION": "Initiate a Claim for Customer Compensation or Financial Refund",
    "COMPENSATION_SECTION": "Department for Service Credit, Refunds, and Compensation Claims",
    "CURRENT_PROVIDER": "Skyline Mobile Telecommunications Provider",
    "CUSTOMER_SUPPORT_NUMBER": "Corporate Customer Care Line: 1-800-555-0199",
    "DATA_SECTION": "Official Mobile Data Usage Monitoring and Compliance Records",
    "DAYS_NUMBER": "5 Business Days (Processing Timeframe)",
    "DEACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Deactivate All Enhanced Call Forwarding, Blocking, and Screening Features",
    "DEACTIVATE_PHONE_OPTION": "Request Device Suspension from Core Telecommunications Network",
    "DEVICE_SECTION": "Enterprise-Registered Devices and Authorized Equipment Catalog",
    "DEVICE_TYPE": "Latest Generation Corporate-Grade 5G Smartphone",
    "DISPUTE_INVOICE_OPTION": "Initiate Formal Invoice Dispute and Investigation Request",
    "EDIT_OPTION": "Edit Official Account Preferences and Corporate Information",
    "FEE_OPTION": "List of Applicable Tariffs, Surcharges, and Administrative Fees",
    "HUMAN_AGENT_OPTION": "Escalate Request to Licensed Human Customer Support Agent",
    "INFORMATION_DATA_CHARGES_SECTION": "Reference Document on Mobile Data Usage and Applicable Fees",
    "INTERNATIONAL_ROAMING_OPTION": "Enable International Roaming in Accordance with Travel Policy",
    "INTERNET_SECTION": "Fixed-Line and Broadband Internet Service Information",
    "INVOICE_SECTION": "Detailed Invoice History and Comprehensive Billing Archive",
    "MANAGEMENT_SERVICES_SECTION": "Centralized Call and Data Management Services Dashboard",
    "MY_ACCOUNT_SECTION": "Secure Customer Account Access Portal",
    "NEW_PROVIDER": "NovaTel Wireless Services Provider",
    "NO_VOICEMAIL": "Voicemail Functionality Disabled by Policy",
    "PAYMENT_HISTORY_OPTION": "Retrieve Archived Payment Transactions and Receipts",
    "PAYMENT_METHODS_OPTION": "Manage Bank Transfer, Credit, and Debit Payment Methods",
    "PAYMENT_SECTION": "Payments and Transaction Management Center",
    "PLAN_SECTION": "Mobile Service Plans and Subscription Management Center",
    "PORTING_CODE": "PORT-987654321-VALID-FOR-7-DAYS",
    "REPORT_POOR_SIGNAL_COVERAGE_OPTION": "Submit Formal Report for Signal Coverage Deficiencies",
    "REPORT_PROBLEM_OPTION": "Log Service Issue or Technical Problem Report",
    "ROAMING_SECTION": "Roaming Services Information and Usage Compliance",
    "SCHEDULE_PAYMENTS_OPTION": "Configure Scheduled or Recurring Payments via Account Portal",
    "SEARCH_BUTTON": "Search Internal Information and Service Catalog",
    "SERVICE_TYPE": "Mobile Voice and Data Communication Service",
    "SIGNAL_COVERAGE_SECTION": "Signal Coverage and Network Availability Reference Maps",
    "SIGN_UP_BUTTON": "Register for a New Subscription Plan",
    "SUPPORT_EMAIL_ADDRESS": "customer.support@globaltel.com",
    "SUPPORT_SECTION": "Customer Support and Service Resolution Division",
    "SUPPORT_TEAM_CONTACT": "Official Support Team Contact Information",
    "SWITCH_ON_OPTION": "Activate Requested Service Feature",
    "USAGE_INFORMATION_OPTION": "Access Consumption Data and Detailed Usage Records",
    "USAGE_SECTION": "Service Consumption and Data Usage Tracking System",
    "VIEW_PAST_BILLS": "Retrieve Archived Billing Records and Payment Documentation",
    "VOICEMAIL": "Voicemail Message Repository and Access Console",
    "WEBSITE_URL": "www.globaltel-communications.com"
}

PLACEHOLDER_VALUES_P2 = {
    "ACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Switch On Spam Shield, Quick Forward, and Instant Screen",
    "ACTIVATION_SECTION": "Start-Up Zone",
    "APP": "PocketTalk App — Chat, Bills, Rewards",
    "BILLING_SECTION": "Money Page",
    "CALL_ALERT": "Buzz Me When I Miss Calls",
    "CANCELLATION_FEES_SUBSECTION": "Quit Costs",
    "CANCEL_PLAN_OPTION": "End My Bundle Now",
    "CANCEL_SECTION": "Exit Hub",
    "CHANGE_PLAN_OPTION": "Pick Another Deal",
    "CHECK_EXCESS_DATA_CHARGES_OPTION": "Extra Costs Log",
    "COMPANY": "TalkNow Crew",
    "COMPENSATION_REQUEST_OPTION": "Get Cashback",
    "COMPENSATION_SECTION": "Rewards Zone",
    "CURRENT_PROVIDER": "MetroWave",
    "CUSTOMER_SUPPORT_NUMBER": "Hotline: +1-888-777-4242",
    "DATA_SECTION": "Consumption Tracker",
    "DAYS_NUMBER": "Two Weeks",
    "DEACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Turn Filters Off",
    "DEACTIVATE_PHONE_OPTION": "Shut My Line",
    "DEVICE_SECTION": "Gadget Locker",
    "DEVICE_TYPE": "Foldable Pocket Device",
    "DISPUTE_INVOICE_OPTION": "Fix My Bill",
    "EDIT_OPTION": "Update Profile",
    "FEE_OPTION": "Charges List",
    "HUMAN_AGENT_OPTION": "Talk to a Person",
    "INFORMATION_DATA_CHARGES_SECTION": "Overage Guide",
    "INTERNATIONAL_ROAMING_OPTION": "Travel Pack",
    "INTERNET_SECTION": "Superfast Deals",
    "INVOICE_SECTION": "Bills Archive",
    "MANAGEMENT_SERVICES_SECTION": "Control Hub",
    "MY_ACCOUNT_SECTION": "Dashboard",
    "NEW_PROVIDER": "HorizonCell",
    "NO_VOICEMAIL": "No Voicemail",
    "PAYMENT_HISTORY_OPTION": "Payment Log",
    "PAYMENT_METHODS_OPTION": "Change Cards",
    "PAYMENT_SECTION": "Pay Here",
    "PLAN_SECTION": "Browse Bundles",
    "PORTING_CODE": "MOVE-NEW-999",
    "REPORT_POOR_SIGNAL_COVERAGE_OPTION": "Bad Signal Ticket",
    "REPORT_PROBLEM_OPTION": "Something’s Wrong",
    "ROAMING_SECTION": "Travel Add-Ons",
    "SCHEDULE_PAYMENTS_OPTION": "Auto-Pay Setup",
    "SEARCH_BUTTON": "Find Now",
    "SERVICE_TYPE": "Talk + Net Pack",
    "SIGNAL_COVERAGE_SECTION": "5G/6G Map",
    "SIGN_UP_BUTTON": "Join Instantly",
    "SUPPORT_EMAIL_ADDRESS": "care@talknow.net",
    "SUPPORT_SECTION": "Help Hub",
    "SUPPORT_TEAM_CONTACT": "Reach Crew",
    "SWITCH_ON_OPTION": "Turn It On",
    "USAGE_INFORMATION_OPTION": "Check My Use",
    "USAGE_SECTION": "Live Feed",
    "VIEW_PAST_BILLS": "Old Bills Log",
    "VOICEMAIL": "Inbox",
    "WEBSITE_URL": "www.talknow.net"
}

PLACEHOLDER_VALUES_P3 = {
    "ACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Activate Advanced Call Management Features for Outgoing and Incoming Calls",
    "ACTIVATION_SECTION": "Authorized Service Activation and Client Onboarding Portal",
    "APP": "TelcoConnect Mobile Platform for Comprehensive Account Oversight",
    "BILLING_SECTION": "Centralized Billing, Invoice Review, and Reconciliation Center",
    "CALL_ALERT": "Standard Voicemail and Missed Call Alert Notification System",
    "CANCELLATION_FEES_SUBSECTION": "Guidelines Regarding Early Termination Penalties and Related Fees",
    "CANCEL_PLAN_OPTION": "Submit Official Request for Plan Termination and Service Cancellation",
    "CANCEL_SECTION": "Account Termination and Cancellation Processing Department",
    "CHANGE_PLAN_OPTION": "Request Service Subscription Adjustment via Upgrade or Downgrade",
    "CHECK_EXCESS_DATA_CHARGES_OPTION": "Audit and Examine All Additional Data Usage Charges",
    "COMPANY": "GlobalTel Communications Corporation",
    "COMPENSATION_REQUEST_OPTION": "Initiate Customer Compensation or Refund Claim Request",
    "COMPENSATION_SECTION": "Unit for Service Credits, Refunds, and Customer Compensation",
    "CURRENT_PROVIDER": "Skyline Telecommunications Service Provider",
    "CUSTOMER_SUPPORT_NUMBER": "Corporate Care Line: 1-800-555-0199",
    "DATA_SECTION": "Official Data Usage Monitoring and Compliance Center",
    "DAYS_NUMBER": "Five Business Days (Processing Duration)",
    "DEACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Deactivate Enhanced Call Screening, Blocking, and Forwarding Features",
    "DEACTIVATE_PHONE_OPTION": "Submit Request for Device Suspension from Telecom Network",
    "DEVICE_SECTION": "Registered Devices and Authorized Equipment Directory",
    "DEVICE_TYPE": "Next-Generation Corporate-Grade 5G Smartphone",
    "DISPUTE_INVOICE_OPTION": "Initiate Invoice Review and Dispute Investigation Request",
    "EDIT_OPTION": "Modify Official Account Details and Corporate Preferences",
    "FEE_OPTION": "Comprehensive List of Applicable Fees, Surcharges, and Tariffs",
    "HUMAN_AGENT_OPTION": "Forward Request to Authorized Human Support Representative",
    "INFORMATION_DATA_CHARGES_SECTION": "Reference Guide on Mobile Data Usage and Associated Fees",
    "INTERNATIONAL_ROAMING_OPTION": "Activate International Roaming per Travel Guidelines",
    "INTERNET_SECTION": "Fixed-Line and Broadband Internet Services Overview",
    "INVOICE_SECTION": "Invoice Archive and Detailed Billing Record Repository",
    "MANAGEMENT_SERVICES_SECTION": "Unified Call and Data Management Dashboard",
    "MY_ACCOUNT_SECTION": "Secure Access Portal for Customer Accounts",
    "NEW_PROVIDER": "NovaTel Wireless Telecom Provider",
    "NO_VOICEMAIL": "Voicemail Functionality Disabled by Company Policy",
    "PAYMENT_HISTORY_OPTION": "Retrieve Record of Previous Transactions and Payments",
    "PAYMENT_METHODS_OPTION": "Administer Credit, Debit, and Bank Payment Options",
    "PAYMENT_SECTION": "Transaction and Payment Management Center",
    "PLAN_SECTION": "Service Plans and Subscription Administration Center",
    "PORTING_CODE": "PORT-987654321-ACTIVE-FOR-7-DAYS",
    "REPORT_POOR_SIGNAL_COVERAGE_OPTION": "Submit Official Report on Network Coverage Issues",
    "REPORT_PROBLEM_OPTION": "Log Technical or Service Issue Report",
    "ROAMING_SECTION": "Roaming Information and Policy Compliance Overview",
    "SCHEDULE_PAYMENTS_OPTION": "Set Up Scheduled or Recurring Payment Preferences",
    "SEARCH_BUTTON": "Search Company Information and Service Catalog",
    "SERVICE_TYPE": "Mobile Data and Voice Communication Package",
    "SIGNAL_COVERAGE_SECTION": "Network Availability and Signal Coverage Reference Charts",
    "SIGN_UP_BUTTON": "Enroll for a New Service Subscription",
    "SUPPORT_EMAIL_ADDRESS": "support@globaltel.com",
    "SUPPORT_SECTION": "Customer Assistance and Issue Resolution Division",
    "SUPPORT_TEAM_CONTACT": "Official Support Team Contact Details",
    "SWITCH_ON_OPTION": "Enable Requested Service Function",
    "USAGE_INFORMATION_OPTION": "View Consumption Data and Detailed Usage Records",
    "USAGE_SECTION": "Data Tracking and Service Consumption Monitoring System",
    "VIEW_PAST_BILLS": "Access Archived Billing Statements and Receipts",
    "VOICEMAIL": "Voicemail Message Access and Storage Console",
    "WEBSITE_URL": "https://www.globaltel-communications.com"
}


PLACEHOLDER_VALUES_P4 = {
    "ACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Turn On Spam Guard, Quick Forward, and Instant Screen",
    "ACTIVATION_SECTION": "Setup Corner",
    "APP": "PocketTalk App — Chat, Pay, Earn Rewards",
    "BILLING_SECTION": "The Money Page",
    "CALL_ALERT": "Ping Me for Missed Calls",
    "CANCELLATION_FEES_SUBSECTION": "Leaving Fees",
    "CANCEL_PLAN_OPTION": "End My Plan Now",
    "CANCEL_SECTION": "Exit Center",
    "CHANGE_PLAN_OPTION": "Choose a Different Deal",
    "CHECK_EXCESS_DATA_CHARGES_OPTION": "Extra Usage Log",
    "COMPANY": "TalkNow Team",
    "COMPENSATION_REQUEST_OPTION": "Claim Cashback",
    "COMPENSATION_SECTION": "Bonus Zone",
    "CURRENT_PROVIDER": "MetroWave Network",
    "CUSTOMER_SUPPORT_NUMBER": "Support Line: +1-888-777-4242",
    "DATA_SECTION": "Usage Tracker",
    "DAYS_NUMBER": "About Two Weeks",
    "DEACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Switch Filters Off",
    "DEACTIVATE_PHONE_OPTION": "Suspend My Line",
    "DEVICE_SECTION": "Device Locker",
    "DEVICE_TYPE": "Foldable Smart Device",
    "DISPUTE_INVOICE_OPTION": "Dispute My Bill",
    "EDIT_OPTION": "Modify Profile",
    "FEE_OPTION": "Fee List",
    "HUMAN_AGENT_OPTION": "Speak to an Agent",
    "INFORMATION_DATA_CHARGES_SECTION": "Data Overage Guide",
    "INTERNATIONAL_ROAMING_OPTION": "Travel Add-On",
    "INTERNET_SECTION": "Superfast Offers",
    "INVOICE_SECTION": "Bills Log",
    "MANAGEMENT_SERVICES_SECTION": "Main Hub",
    "MY_ACCOUNT_SECTION": "My Dashboard",
    "NEW_PROVIDER": "HorizonCell Network",
    "NO_VOICEMAIL": "Voicemail Off",
    "PAYMENT_HISTORY_OPTION": "Transaction Log",
    "PAYMENT_METHODS_OPTION": "Edit Cards",
    "PAYMENT_SECTION": "Payment Zone",
    "PLAN_SECTION": "Plan Browser",
    "PORTING_CODE": "MOVE-999-NEW",
    "REPORT_POOR_SIGNAL_COVERAGE_OPTION": "Weak Signal Ticket",
    "REPORT_PROBLEM_OPTION": "Report an Issue",
    "ROAMING_SECTION": "Travel Options",
    "SCHEDULE_PAYMENTS_OPTION": "Auto Payment Setup",
    "SEARCH_BUTTON": "Search It",
    "SERVICE_TYPE": "Talk and Net Pack",
    "SIGNAL_COVERAGE_SECTION": "Coverage Map (5G/6G)",
    "SIGN_UP_BUTTON": "Join Now",
    "SUPPORT_EMAIL_ADDRESS": "help@talknow.net",
    "SUPPORT_SECTION": "Help Center",
    "SUPPORT_TEAM_CONTACT": "Contact Team",
    "SWITCH_ON_OPTION": "Activate It",
    "USAGE_INFORMATION_OPTION": "See My Usage",
    "USAGE_SECTION": "Live Tracker",
    "VIEW_PAST_BILLS": "Previous Bills Log",
    "VOICEMAIL": "Message Box",
    "WEBSITE_URL": "https://www.talknow.net"
}
PLACEHOLDER_VALUES_P5 = {
    "ACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Enable Advanced Call Management Tools for Incoming and Outgoing Calls",
    "ACTIVATION_SECTION": "Primary Service Activation and User Onboarding Portal",
    "APP": "TelcoConnect Mobile App for Full Account Management",
    "BILLING_SECTION": "Central Billing and Reconciliation Department",
    "CALL_ALERT": "Standard Notification for Missed Calls and Voicemail Alerts",
    "CANCELLATION_FEES_SUBSECTION": "Policy on Early Service Termination and Applicable Fees",
    "CANCEL_PLAN_OPTION": "Submit Official Request for Service Termination and Plan Cancellation",
    "CANCEL_SECTION": "Service Cancellation and Account Closure Division",
    "CHANGE_PLAN_OPTION": "Submit Request to Modify Subscription via Upgrade or Downgrade",
    "CHECK_EXCESS_DATA_CHARGES_OPTION": "Inspect and Review Additional Mobile Data Usage Fees",
    "COMPANY": "GlobalTel Communications Ltd.",
    "COMPENSATION_REQUEST_OPTION": "File Request for Refund or Service Compensation",
    "COMPENSATION_SECTION": "Department for Credits, Refunds, and Customer Compensation",
    "CURRENT_PROVIDER": "Skyline Mobile Telecom Provider",
    "CUSTOMER_SUPPORT_NUMBER": "Customer Care Line: 1-800-555-0199",
    "DATA_SECTION": "Official Data Monitoring and Compliance Registry",
    "DAYS_NUMBER": "Processing Period: Five Business Days",
    "DEACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Disable Enhanced Forwarding, Blocking, and Screening Services",
    "DEACTIVATE_PHONE_OPTION": "Initiate Device Suspension from Core Telecom Network",
    "DEVICE_SECTION": "Registered Devices and Approved Equipment List",
    "DEVICE_TYPE": "Advanced Corporate-Grade 5G Smartphone",
    "DISPUTE_INVOICE_OPTION": "Request Invoice Dispute or Formal Review",
    "EDIT_OPTION": "Update Registered Account Information and Preferences",
    "FEE_OPTION": "List of Administrative Fees, Tariffs, and Surcharges",
    "HUMAN_AGENT_OPTION": "Connect with Licensed Human Support Representative",
    "INFORMATION_DATA_CHARGES_SECTION": "Guide on Mobile Data Usage Fees and Limits",
    "INTERNATIONAL_ROAMING_OPTION": "Activate International Roaming Following Travel Policy",
    "INTERNET_SECTION": "Broadband and Fixed Internet Service Overview",
    "INVOICE_SECTION": "Comprehensive Billing Archive and Invoice Records",
    "MANAGEMENT_SERVICES_SECTION": "Integrated Dashboard for Call and Data Management",
    "MY_ACCOUNT_SECTION": "Secure Customer Account Management Portal",
    "NEW_PROVIDER": "NovaTel Wireless Carrier",
    "NO_VOICEMAIL": "Voicemail Access Disabled per Policy",
    "PAYMENT_HISTORY_OPTION": "Access Historical Payment Receipts and Records",
    "PAYMENT_METHODS_OPTION": "Manage Credit, Debit, or Bank Transfer Options",
    "PAYMENT_SECTION": "Payment Processing and Management Center",
    "PLAN_SECTION": "Subscription and Plan Management Portal",
    "PORTING_CODE": "PORT-987654321-VALID-FOR-SEVEN-DAYS",
    "REPORT_POOR_SIGNAL_COVERAGE_OPTION": "File Report for Weak or Poor Network Coverage",
    "REPORT_PROBLEM_OPTION": "Submit Technical or Service Issue Log",
    "ROAMING_SECTION": "Information Hub for Roaming Policies and Usage",
    "SCHEDULE_PAYMENTS_OPTION": "Set Up Recurring Payment Schedule",
    "SEARCH_BUTTON": "Locate Service or Information",
    "SERVICE_TYPE": "Mobile Data and Voice Communication Package",
    "SIGNAL_COVERAGE_SECTION": "Network Coverage and Availability Reference Maps",
    "SIGN_UP_BUTTON": "Sign Up for a New Plan",
    "SUPPORT_EMAIL_ADDRESS": "assist@globaltel.com",
    "SUPPORT_SECTION": "Support and Service Resolution Center",
    "SUPPORT_TEAM_CONTACT": "Corporate Support Contact Details",
    "SWITCH_ON_OPTION": "Activate the Requested Service",
    "USAGE_INFORMATION_OPTION": "Access Usage Details and Data Records",
    "USAGE_SECTION": "Usage Tracking and Monitoring Dashboard",
    "VIEW_PAST_BILLS": "Retrieve Old Billing Statements and Payment Records",
    "VOICEMAIL": "Voicemail Access and Storage Portal",
    "WEBSITE_URL": "https://www.globaltel-communications.com"
}

PLACEHOLDER_VALUES_P6 = {
    "ACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Turn On Smart Shield, Quick Forward, and Instant Screen",
    "ACTIVATION_SECTION": "Setup Zone",
    "APP": "PocketTalk App — Chat, Billing, Rewards",
    "BILLING_SECTION": "Money Dashboard",
    "CALL_ALERT": "Notify Me When Calls Are Missed",
    "CANCELLATION_FEES_SUBSECTION": "Early Quit Fees",
    "CANCEL_PLAN_OPTION": "Cancel My Bundle Now",
    "CANCEL_SECTION": "Exit Point",
    "CHANGE_PLAN_OPTION": "Switch to Another Deal",
    "CHECK_EXCESS_DATA_CHARGES_OPTION": "Extra Data Log",
    "COMPANY": "TalkNow Network",
    "COMPENSATION_REQUEST_OPTION": "Ask for Cashback",
    "COMPENSATION_SECTION": "Reward Hub",
    "CURRENT_PROVIDER": "MetroWave Telecom",
    "CUSTOMER_SUPPORT_NUMBER": "Help Line: +1-888-777-4242",
    "DATA_SECTION": "Data Tracker",
    "DAYS_NUMBER": "Roughly Two Weeks",
    "DEACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Turn Call Filters Off",
    "DEACTIVATE_PHONE_OPTION": "Deactivate My Line",
    "DEVICE_SECTION": "Device Storage",
    "DEVICE_TYPE": "Foldable Mobile Device",
    "DISPUTE_INVOICE_OPTION": "Correct My Bill",
    "EDIT_OPTION": "Revise Profile",
    "FEE_OPTION": "Charges Overview",
    "HUMAN_AGENT_OPTION": "Chat with an Agent",
    "INFORMATION_DATA_CHARGES_SECTION": "Overage Info",
    "INTERNATIONAL_ROAMING_OPTION": "Roaming Add-On",
    "INTERNET_SECTION": "High-Speed Plans",
    "INVOICE_SECTION": "Billing Archive",
    "MANAGEMENT_SERVICES_SECTION": "Main Control Hub",
    "MY_ACCOUNT_SECTION": "User Dashboard",
    "NEW_PROVIDER": "HorizonCell Plus",
    "NO_VOICEMAIL": "Voicemail Disabled",
    "PAYMENT_HISTORY_OPTION": "Payment Summary",
    "PAYMENT_METHODS_OPTION": "Manage Cards",
    "PAYMENT_SECTION": "Payment Hub",
    "PLAN_SECTION": "Available Bundles",
    "PORTING_CODE": "MOVE-NEW-999-V2",
    "REPORT_POOR_SIGNAL_COVERAGE_OPTION": "Report Weak Signal",
    "REPORT_PROBLEM_OPTION": "Flag an Issue",
    "ROAMING_SECTION": "Travel Add-Ons List",
    "SCHEDULE_PAYMENTS_OPTION": "Setup Auto-Pay",
    "SEARCH_BUTTON": "Find It",
    "SERVICE_TYPE": "Talk & Data Pack",
    "SIGNAL_COVERAGE_SECTION": "5G and 6G Map",
    "SIGN_UP_BUTTON": "Join Instantly Now",
    "SUPPORT_EMAIL_ADDRESS": "support@talknow.net",
    "SUPPORT_SECTION": "Assistance Center",
    "SUPPORT_TEAM_CONTACT": "Get in Touch",
    "SWITCH_ON_OPTION": "Activate Now",
    "USAGE_INFORMATION_OPTION": "Check Data Use",
    "USAGE_SECTION": "Live Usage Feed",
    "VIEW_PAST_BILLS": "Old Payment Records",
    "VOICEMAIL": "Voicemail Inbox",
    "WEBSITE_URL": "https://www.talknow.net"
}
