PLACEHOLDER_VALUES_P1 = {
    "COMPANY": "GlobalTel Communications Incorporated",
    "APP": "TelcoConnect Mobile Application for Customer Account Management",
    "BILLING_SECTION": "Billing and Invoice Management Section",
    "CALL_ALERT": "Missed Call and Voicemail Alert Notifications",
    "CANCELLATION_FEES_SUBSECTION": "Early Termination and Plan Cancellation Fee Details",
    "CANCEL_PLAN_OPTION": "Request Full Plan Cancellation and Service Termination",
    "CANCEL_SECTION": "Cancellation and Service Termination Center",
    "CHANGE_PLAN_OPTION": "Upgrade or Downgrade to a New Mobile Service Plan",
    "CHECK_EXCESS_DATA_CHARGES_OPTION": "Check and Review Excess Mobile Data Usage Charges",
    "COMPENSATION_REQUEST_OPTION": "Submit Customer Compensation or Refund Request",
    "COMPENSATION_SECTION": "Compensation, Refunds, and Service Guarantee Section",
    "CURRENT_PROVIDER": "Skyline Mobile Telecommunications Provider",
    "CUSTOMER_SUPPORT_NUMBER": "Toll-Free Customer Support Hotline: 1-800-555-0199",
    "DATA_SECTION": "Mobile Data Usage and Monitoring Section",
    "DAYS_NUMBER": "5 Business Days",
    "DEACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Deactivate All Call Forwarding and Call Blocking Services",
    "DEACTIVATE_PHONE_OPTION": "Deactivate or Suspend Mobile Device from Network",
    "DEVICE_SECTION": "Connected Devices and Device Management Section",
    "DEVICE_TYPE": "Latest Generation 5G-Enabled Smartphone",
    "DISPUTE_INVOICE_OPTION": "Dispute This Invoice and Request Investigation",
    "EDIT_OPTION": "Edit Account Preferences and Personal Details",
    "FEE_OPTION": "View All Applicable Fees and Surcharges",
    "HUMAN_AGENT_OPTION": "Talk Directly to a Live Human Customer Service Agent",
    "INFORMATION_DATA_CHARGES_SECTION": "Detailed Information on Data Usage and Additional Charges",
    "INTERNATIONAL_ROAMING_OPTION": "Enable International Roaming and Travel Data Services",
    "INTERNET_SECTION": "Internet and Broadband Service Information",
    "INVOICE_SECTION": "Invoice History and Current Billing Records",
    "MANAGEMENT_SERVICES_SECTION": "Call and Data Management Services Overview",
    "MY_ACCOUNT_SECTION": "My Account Dashboard and User Profile Section",
    "NEW_PROVIDER": "NovaTel Wireless Services Provider",
    "NO_VOICEMAIL": "Voicemail Services Not Currently Enabled",
    "PAYMENT_HISTORY_OPTION": "View Complete Payment History and Transactions",
    "PAYMENT_METHODS_OPTION": "Manage Credit Card, Debit Card, and Bank Transfer Payment Methods",
    "PAYMENT_SECTION": "Payments and Transaction Management Center",
    "PLAN_SECTION": "Mobile Plans and Subscription Options Section",
    "PORTING_CODE": "PORT-987654321-VALID-FOR-7-DAYS",
    "REPORT_POOR_SIGNAL_COVERAGE_OPTION": "Report Poor Signal or Network Coverage Issues",
    "REPORT_PROBLEM_OPTION": "Report Any Service Problem or Technical Difficulty",
    "ROAMING_SECTION": "Roaming and International Travel Service Section",
    "SCHEDULE_PAYMENTS_OPTION": "Schedule Future Payments or Automatic Bill Pay",
    "SEARCH_BUTTON": "Search for Information or Services",
    "SERVICE_TYPE": "Mobile Communication and Data Service",
    "SIGNAL_COVERAGE_SECTION": "Signal Coverage and Network Availability Maps",
    "SIGN_UP_BUTTON": "Sign Up for a New Account and Subscription Plan",
    "SUPPORT_EMAIL_ADDRESS": "customer.support@globaltel.com",
    "SUPPORT_SECTION": "Customer Support and Helpdesk Services",
    "SUPPORT_TEAM_CONTACT": "Contact Our Customer Support Team for Assistance",
    "SWITCH_ON_OPTION": "Turn On or Enable This Feature",
    "USAGE_INFORMATION_OPTION": "Access Usage Information and Detailed Consumption Reports",
    "USAGE_SECTION": "Usage Tracking and Service Consumption Section",
    "VIEW_PAST_BILLS": "View and Download Past Bills and Payment Records",
    "VOICEMAIL": "Voicemail Inbox and Message Management",
    "WEBSITE_URL": "www.globaltel-communications.com"
}

PLACEHOLDER_VALUES_P2 = {
    "COMPANY": "GlobalTel Communications Company",
    "APP": "TelcoConnect Mobile App for Account Management",
    "BILLING_SECTION": "Billing and Invoice Center",
    "CALL_ALERT": "Missed Call Notifications and Alerts",
    "CANCELLATION_FEES_SUBSECTION": "Plan Cancellation and Fee Details",
    "CANCEL_PLAN_OPTION": "Request Plan Cancellation",
    "CANCEL_SECTION": "Plan Cancellation Center",
    "CHANGE_PLAN_OPTION": "Change Your Service Plan",
    "CHECK_EXCESS_DATA_CHARGES_OPTION": "Check Extra Data Usage Charges",
    "COMPENSATION_REQUEST_OPTION": "Request Customer Compensation",
    "COMPENSATION_SECTION": "Refunds and Compensation Section",
    "CURRENT_PROVIDER": "Skyline Telecom",
    "CUSTOMER_SUPPORT_NUMBER": "Customer Support Hotline: 1-800-555-1234",
    "DATA_SECTION": "Data Usage and Monitoring",
    "DAYS_NUMBER": "7 Business Days",
    "DEACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Turn Off Call Management Services",
    "DEACTIVATE_PHONE_OPTION": "Suspend Mobile Device from Network",
    "DEVICE_SECTION": "Device Management Section",
    "DEVICE_TYPE": "5G-Enabled Smartphone",
    "DISPUTE_INVOICE_OPTION": "Dispute Invoice Request",
    "EDIT_OPTION": "Update Account Preferences",
    "FEE_OPTION": "View All Fees",
    "HUMAN_AGENT_OPTION": "Speak to a Live Agent",
    "INFORMATION_DATA_CHARGES_SECTION": "Information on Data Charges",
    "INTERNATIONAL_ROAMING_OPTION": "Activate International Roaming",
    "INTERNET_SECTION": "Internet Service Information",
    "INVOICE_SECTION": "Invoice Records",
    "MANAGEMENT_SERVICES_SECTION": "Service Management Overview",
    "MY_ACCOUNT_SECTION": "Account Dashboard",
    "NEW_PROVIDER": "NovaTel Provider",
    "NO_VOICEMAIL": "Voicemail Not Enabled",
    "PAYMENT_HISTORY_OPTION": "View Payment History",
    "PAYMENT_METHODS_OPTION": "Manage Payment Methods",
    "PAYMENT_SECTION": "Payments Center",
    "PLAN_SECTION": "Plans and Options",
    "PORTING_CODE": "PORT-111111111-VALID-FOR-10-DAYS",
    "REPORT_POOR_SIGNAL_COVERAGE_OPTION": "Report Network Coverage Issues",
    "REPORT_PROBLEM_OPTION": "Report Service Problem",
    "ROAMING_SECTION": "Roaming Service Section",
    "SCHEDULE_PAYMENTS_OPTION": "Schedule Payments",
    "SEARCH_BUTTON": "Search Services",
    "SERVICE_TYPE": "Mobile Data Service",
    "SIGNAL_COVERAGE_SECTION": "Network Coverage Maps",
    "SIGN_UP_BUTTON": "Sign Up for an Account",
    "SUPPORT_EMAIL_ADDRESS": "support@globaltel.com",
    "SUPPORT_SECTION": "Support Services",
    "SUPPORT_TEAM_CONTACT": "Contact Customer Support Team",
    "SWITCH_ON_OPTION": "Enable Feature",
    "USAGE_INFORMATION_OPTION": "Usage Information Reports",
    "USAGE_SECTION": "Usage Tracking Section",
    "VIEW_PAST_BILLS": "View Past Bills",
    "VOICEMAIL": "Voicemail Management",
    "WEBSITE_URL": "www.globaltel-connect.com"
}

PLACEHOLDER_VALUES_P3 = {
    "COMPANY": "GlobalTel Telecom Services",
    "APP": "TelcoConnect Account Manager App",
    "BILLING_SECTION": "Billing and Payments Hub",
    "CALL_ALERT": "Voicemail and Call Alerts",
    "CANCELLATION_FEES_SUBSECTION": "Termination Fees and Plan Cancellation",
    "CANCEL_PLAN_OPTION": "End Plan Subscription",
    "CANCEL_SECTION": "Service Termination Section",
    "CHANGE_PLAN_OPTION": "Switch to a New Plan",
    "CHECK_EXCESS_DATA_CHARGES_OPTION": "Review Data Overage Charges",
    "COMPENSATION_REQUEST_OPTION": "Submit Refund or Credit Request",
    "COMPENSATION_SECTION": "Service Credits and Refunds Section",
    "CURRENT_PROVIDER": "Metro Telecom Provider",
    "CUSTOMER_SUPPORT_NUMBER": "Customer Hotline: 1-800-222-9876",
    "DATA_SECTION": "Data Services and Monitoring",
    "DAYS_NUMBER": "10 Business Days",
    "DEACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Disable Call Blocking Services",
    "DEACTIVATE_PHONE_OPTION": "Deactivate Device",
    "DEVICE_SECTION": "Mobile Device Section",
    "DEVICE_TYPE": "5G Foldable Smartphone",
    "DISPUTE_INVOICE_OPTION": "Raise Invoice Dispute",
    "EDIT_OPTION": "Edit Profile Settings",
    "FEE_OPTION": "List of Fees",
    "HUMAN_AGENT_OPTION": "Chat with a Human Agent",
    "INFORMATION_DATA_CHARGES_SECTION": "Guide to Data Charges",
    "INTERNATIONAL_ROAMING_OPTION": "Enable Global Roaming",
    "INTERNET_SECTION": "Broadband Internet Info",
    "INVOICE_SECTION": "Billing Records Archive",
    "MANAGEMENT_SERVICES_SECTION": "Telecom Services Overview",
    "MY_ACCOUNT_SECTION": "User Dashboard",
    "NEW_PROVIDER": "Horizon Wireless",
    "NO_VOICEMAIL": "Voicemail Disabled",
    "PAYMENT_HISTORY_OPTION": "Check Payment Records",
    "PAYMENT_METHODS_OPTION": "Update Payment Options",
    "PAYMENT_SECTION": "Transaction Center",
    "PLAN_SECTION": "Subscription Packages",
    "PORTING_CODE": "PORT-222222222-VALID-FOR-12-DAYS",
    "REPORT_POOR_SIGNAL_COVERAGE_OPTION": "Log Poor Coverage Issue",
    "REPORT_PROBLEM_OPTION": "Open Service Ticket",
    "ROAMING_SECTION": "International Roaming Section",
    "SCHEDULE_PAYMENTS_OPTION": "Auto-Payment Scheduler",
    "SEARCH_BUTTON": "Search Info",
    "SERVICE_TYPE": "Telecom Data Service",
    "SIGNAL_COVERAGE_SECTION": "Coverage Availability",
    "SIGN_UP_BUTTON": "Register for a Plan",
    "SUPPORT_EMAIL_ADDRESS": "help@globaltel.com",
    "SUPPORT_SECTION": "Help Services",
    "SUPPORT_TEAM_CONTACT": "Reach Customer Team",
    "SWITCH_ON_OPTION": "Switch On Feature",
    "USAGE_INFORMATION_OPTION": "Detailed Usage Reports",
    "USAGE_SECTION": "Consumption Tracker",
    "VIEW_PAST_BILLS": "Access Previous Bills",
    "VOICEMAIL": "Voice Messaging",
    "WEBSITE_URL": "www.globaltel-services.net"
}

PLACEHOLDER_VALUES_P4 = {
    "COMPANY": "TalkNow Cellular Group",
    "APP": "TalkNow MyMobile App",
    "BILLING_SECTION": "Payments and Statements Center",
    "CALL_ALERT": "Instant Call Alerts",
    "CANCELLATION_FEES_SUBSECTION": "Plan Exit Fee Details",
    "CANCEL_PLAN_OPTION": "Terminate Subscription",
    "CANCEL_SECTION": "Account Termination Division",
    "CHANGE_PLAN_OPTION": "Modify Subscription",
    "CHECK_EXCESS_DATA_CHARGES_OPTION": "Analyze Data Charges",
    "COMPENSATION_REQUEST_OPTION": "Request Service Compensation",
    "COMPENSATION_SECTION": "Customer Refunds Division",
    "CURRENT_PROVIDER": "TalkNow Carrier",
    "CUSTOMER_SUPPORT_NUMBER": "TalkNow Hotline: +1-877-888-9999",
    "DATA_SECTION": "Network Data Hub",
    "DAYS_NUMBER": "14 Days",
    "DEACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Remove Call Controls",
    "DEACTIVATE_PHONE_OPTION": "Completely Disable Device",
    "DEVICE_SECTION": "Devices Hub",
    "DEVICE_TYPE": "Foldable 5G Smartphone",
    "DISPUTE_INVOICE_OPTION": "File Billing Complaint",
    "EDIT_OPTION": "Change Account Preferences",
    "FEE_OPTION": "Charges & Fees",
    "HUMAN_AGENT_OPTION": "Connect to a Human Representative",
    "INFORMATION_DATA_CHARGES_SECTION": "Data Charges Handbook",
    "INTERNATIONAL_ROAMING_OPTION": "Activate Global Plans",
    "INTERNET_SECTION": "TalkNow Broadband Info",
    "INVOICE_SECTION": "Billing History Records",
    "MANAGEMENT_SERVICES_SECTION": "Telecom Management Hub",
    "MY_ACCOUNT_SECTION": "TalkNow User Portal",
    "NEW_PROVIDER": "ZapTel Provider",
    "NO_VOICEMAIL": "Voicemail Feature Off",
    "PAYMENT_HISTORY_OPTION": "Check All Transactions",
    "PAYMENT_METHODS_OPTION": "Manage Banking Options",
    "PAYMENT_SECTION": "Payment Transactions",
    "PLAN_SECTION": "Tiered Subscription Packages",
    "PORTING_CODE": "PORT-333333333-VALID-FOR-14-DAYS",
    "REPORT_POOR_SIGNAL_COVERAGE_OPTION": "Submit Coverage Issue",
    "REPORT_PROBLEM_OPTION": "Report Technical Issue",
    "ROAMING_SECTION": "Roaming Portal",
    "SCHEDULE_PAYMENTS_OPTION": "Setup Recurring Payments",
    "SEARCH_BUTTON": "Search Options",
    "SERVICE_TYPE": "TalkNow Data and Voice",
    "SIGNAL_COVERAGE_SECTION": "TalkNow Coverage Maps",
    "SIGN_UP_BUTTON": "Enroll for TalkNow Service",
    "SUPPORT_EMAIL_ADDRESS": "support@talknow.com",
    "SUPPORT_SECTION": "Customer Help Desk",
    "SUPPORT_TEAM_CONTACT": "TalkNow Support Team",
    "SWITCH_ON_OPTION": "Turn Feature On",
    "USAGE_INFORMATION_OPTION": "Track Usage Reports",
    "USAGE_SECTION": "Usage Monitor",
    "VIEW_PAST_BILLS": "Review Old Bills",
    "VOICEMAIL": "TalkNow Voicemail",
    "WEBSITE_URL": "www.talknow-wireless.net"
}

PLACEHOLDER_VALUES_P5 = {
    "COMPANY": "ZapTalk Wireless Collective",
    "APP": "ZapGo App — Chat, Pay & Perks",
    "BILLING_SECTION": "MoneyBlast Hub",
    "CALL_ALERT": "BuzzPing Alerts",
    "CANCELLATION_FEES_SUBSECTION": "Exit Penalty Zone",
    "CANCEL_PLAN_OPTION": "Drop My Bundle",
    "CANCEL_SECTION": "ZapExit Hub",
    "CHANGE_PLAN_OPTION": "Flip My Bundle",
    "CHECK_EXCESS_DATA_CHARGES_OPTION": "Overload Fee Checker",
    "COMPENSATION_REQUEST_OPTION": "Claim Reward Credits",
    "COMPENSATION_SECTION": "ZapCash Zone",
    "CURRENT_PROVIDER": "ZapCrew Net",
    "CUSTOMER_SUPPORT_NUMBER": "ZapLine 24/7: +1-800-ZAP-NOW",
    "DATA_SECTION": "StreamBlast Portal",
    "DAYS_NUMBER": "ZapFast — Same Day",
    "DEACTIVATE_CALL_MANAGEMENT_SERVICES_OPTION": "Shut Down Call Mods",
    "DEACTIVATE_PHONE_OPTION": "Pull Device Offline",
    "DEVICE_SECTION": "GadgetSphere",
    "DEVICE_TYPE": "ZapPhone Max Ultra",
    "DISPUTE_INVOICE_OPTION": "BillFight Zone",
    "EDIT_OPTION": "Tweak My Profile",
    "FEE_OPTION": "Money Matters Board",
    "HUMAN_AGENT_OPTION": "Ping a ZapHuman",
    "INFORMATION_DATA_CHARGES_SECTION": "ZapRules Board",
    "INTERNATIONAL_ROAMING_OPTION": "ZapRoam Anywhere",
    "INTERNET_SECTION": "NetBlast Portal",
    "INVOICE_SECTION": "PastPay Archive",
    "MANAGEMENT_SERVICES_SECTION": "Zap Control Deck",
    "MY_ACCOUNT_SECTION": "Profile Hub",
    "NEW_PROVIDER": "ZapTalk NextGen",
    "NO_VOICEMAIL": "Voicemail Dropped",
    "PAYMENT_HISTORY_OPTION": "MoneyTrail Logs",
    "PAYMENT_METHODS_OPTION": "ZapWallet Manager",
    "PAYMENT_SECTION": "ZapPay Hub",
    "PLAN_SECTION": "ZapBundles — Talk & Data Packs",
    "PORTING_CODE": "PORT-ZAPMAX-1DAY",
    "REPORT_POOR_SIGNAL_COVERAGE_OPTION": "ZapCoverage Shout",
    "REPORT_PROBLEM_OPTION": "ZapFix Request",
    "ROAMING_SECTION": "ZapRoam Portal",
    "SCHEDULE_PAYMENTS_OPTION": "AutoZap Scheduler",
    "SEARCH_BUTTON": "ZapSearch",
    "SERVICE_TYPE": "ZapPack Unlimited",
    "SIGNAL_COVERAGE_SECTION": "ZapCoverage Maps",
    "SIGN_UP_BUTTON": "JoinZap Now",
    "SUPPORT_EMAIL_ADDRESS": "help@zaptalk.net",
    "SUPPORT_SECTION": "HelpBlast 24/7",
    "SUPPORT_TEAM_CONTACT": "ZapCrew Hotline",
    "SWITCH_ON_OPTION": "Zap It",
    "USAGE_INFORMATION_OPTION": "UsageBlast Insights",
    "USAGE_SECTION": "ZapTracker",
    "VIEW_PAST_BILLS": "OldZap Bills",
    "VOICEMAIL": "VoiceDrops",
    "WEBSITE_URL": "www.zaptalk-blast.net"
}

